print("sum of n number")
print("----------------")
n=int(input("enter the n value:"))
print("result")
sum=n*(n+1/2)
print("sum:",sum)
square=n*(n+1)*(2*n+1)/6
print("sum of square:",square)
cube=(n*(n+1)/2)*(n*(n+1)/2)
print("sum of cube:",cube)
