print("exponential program")
print("___________________")
x=int(input("enter x value:"))
y=int(input("enter y value:"))
z=int(input("enter z value:"))
print("result:")
p=((x*x)+(y*y)+(z*z))
print("p=",p)
q=((x*x*x)+(y*y)+z+20)
print("q=",q)
r=((x*x)*y+(y*y)*z*10)
print("r=",r)
s=((x*x*x)*(y*y)*z+2*x*y*z*x*y*z)
print=("s=",s)
